#!/usr/bin/env python3
"""生成带分组的 SUMMARY.md，而不是平铺列表"""
import os

wiki = os.path.expanduser("~/kernel-design-book/wiki/src")

# 定义每个分类下的子分组
# (分组标题, [页文件名前缀列表])
categories = {
    "permission": [
        ("核心概念", ["access-control", "least-privilege", "attenuation", "delegation",
                     "revocation", "capability", "acl", "label", "root-of-trust",
                     "access-control-matrix", "authority", "audit", "temporal",
                     "permission-borrow", "ipc-permission", "delegation-chain",
                     "ambient-authority", "capability-ownership", "security-context",
                     "confused-deputy"]),
        ("访问控制模型", ["rbac", "lsm", "seccomp", "type-enforcement", "mls",
                       "lsm-hooks", "lsm-bpf", "secid", "selinux-policy", "selinux-te",
                       "selinux-rbac", "selinux-mls", "selinux-constraint", "selinux-cond",
                       "selinux-avc", "selinux-xattr", "selinux-boolean", "selinux-port",
                       "selinux-fs", "apparmor-policy", "apparmor-profile", "apparmor-cache",
                       "apparmor-impl", "smack-rule", "smack-label", "tomoyo", "tomoyo-impl",
                       "yama", "loadpin", "safe-setid", "integrity", "integrity-arch",
                       "audit", "kernfs"]),
        ("能力系统实现", ["hic-capability", "sel4-cspace", "linux-capability", "cheri-capability",
                       "keycos", "capability-list", "capability-bitmap"]),
        ("安全缓解", ["spectre-v1", "spectre-v2", "meltdown", "l1tf", "mds", "retpoline",
                     "kpti", "smep-smap", "pac", "bti", "shadow-stack", "kaslr", "fgkaslr",
                     "aslr", "stack-protector", "cfi", "mmap_min_addr", "kernel-ro",
                     "ro-after-init", "mem-protect", "strcpy-protect", "overflow-protect",
                     "refcount-overflow"]),
        ("可信计算", ["tee", "tdx-sev", "sgx", "arm-trustzone", "arm-cca", "riscv-tee",
                     "tpm", "tpm2", "tpm-keystore", "tpm-measure", "tpm-attest",
                     "measured-boot", "signed-modules", "kexec-verify", "signed-kernel",
                     "modsign", "kmod-crypto", "kernel-keys", "keyctl", "keyutils",
                     "diglim", "fs-verity", "fs-encryption", "ecryptfs", "encrypted-keys",
                     "trusted-keys", "dm-verity", "dm-integrity", "ima", "ima-appraisal",
                     "ima-measure", "ima-audit", "evm", "evm-integrity"]),
        ("内核安全框架", ["namespaces", "cgroup-ns", "user-ns", "pid-ns", "net-ns",
                        "mount-ns", "container-security", "docker-security", "kata-security",
                        "gvisor-security", "firecracker", "oci-runtime", "cni", "csi", "cri",
                        "seccomp-oci", "capabilities-oci", "mount-propagation", "pivot_root",
                        "chroot", "dbus-policy", "polkit", "landlock", "bpf-lsm"]),
        ("其他 OS 安全", ["windows-acl", "windows-sd", "windows-token", "windows-privilege",
                        "windows-integrity", "windows-uac", "macos-sip", "macos-hardening",
                        "freebsd-mac", "freebsd-jail", "openbsd-pledge", "openbsd-unveil",
                        "openbsd-sec", "hardenedbsd", "pax", "grsec", "android-selinux",
                        "android-perm", "seccomp-bp"]),
        ("硬件接口", ["sbi", "smbios", "uefi", "acpi-methods"]),
    ],
    "scheduling": [
        ("调度基础", ["scheduling", "interrupts", "synchronization", "deadlock", "memory-scheduling",
                     "context-switch", "realtime", "cooperative-sched", "preemptive-sched",
                     "sched-mechanism", "timeslice", "thread-lifecycle", "process-vs-thread"]),
        ("调度器实现", ["cfs", "eevdf", "o1-scheduler", "dl-sched", "rt-sched", "idle-sched",
                       "stop-sched", "vruntime", "runqueue", "sched-policy", "sched-flags",
                       "sched-nice", "sched-features", "sched-tunables"]),
        ("负载与均衡", ["load-balance", "sched-domain", "sched-group", "root-domain",
                        "nohz-idle-balance", "irq-balance", "smp-scheduling", "multicore-sched",
                        "global-vs-local", "proportional-share", "group-scheduling",
                        "cgroups-cpu", "cfs-bandwidth", "rt-group", "bw-control", "cpumask",
                        "affinity", "dynamic-load", "cpu-hotplug", "task-numa", "wt-migration",
                        "migration-thread", "migration-thread-detail", "migration-cost",
                        "misfit-task", "overutilized"]),
        ("负载跟踪", ["pelt", "walt", "load-tracker", "sched-avg", "util-avg", "load-avg",
                     "sched-stats", "sched-stat", "sched-debug"]),
        ("能耗管理", ["energy-aware", "energy-model", "efficiency", "frequency-scaling",
                     "schedutil", "cpufreq-core", "cpufreq-driver", "cpuidle-core",
                     "cpuidle-driver", "cpuidle-governor", "pm-qos", "devfreq",
                     "thermal-throttle", "cpu-idle", "tick-sched", "nohz", "nohz-full",
                     "adaptive-ticks", "hyperthreading"]),
        ("中断与异常", ["softirq-tasklet", "threaded-irq", "workqueue", "workqueue-concurrency",
                       "unbound-wq", "ordered-wq", "nmi", "mce"]),
        ("定时器与时间", ["hrtimer", "timer-wheel", "posix-timer", "sleep-wake", "restart-block"]),
        ("同步原语", ["futex", "futex-internals", "futex-pi", "futex-requeue", "futex-waitv",
                     "completion", "seqlock", "rwlock", "rwlock-internals", "percpu-rwlock",
                     "mutex-api", "rt-mutex", "atomic-ops", "memory-ordering", "lock-free",
                     "hazptr", "seqcount", "stop-machine", "stop-multi"]),
        ("RCU 机制", ["rcu-variants", "rcu-grace", "rcu-callback", "lockdep-rcu"]),
        ("锁验证与调试", ["lockdep-usage", "lockdep-annotations", "lockdep-mmap", "lockdep-hardirq",
                         "lockdep-softirq", "sleep-in-atomic", "preempt-count", "preempt-model",
                         "nested-lock", "lock-ordering", "lock-contention", "percpu-lock",
                         "stack-limit", "large-stack", "vmalloc-stack", "lockstat"]),
        ("内核线程", ["idle-thread", "ksoftirqd", "kworker", "watchdog-thread", "cpuhp-thread"]),
        ("性能工具", ["sysprof", "perf-record", "perf-top", "perf-stat", "perf-stat-col",
                     "perf-probe", "perf-trace", "perf-script", "perf-report", "perf-annotate",
                     "perf-diff", "perf-c2c", "perf-kmem", "perf-sched", "perf-timechart",
                     "perf-bench", "perf-lock", "scheduling-latency", "wake-latency",
                     "preempt-latency", "irq-latency", "context-switch-count", "cache-miss"]),
        ("追踪 (ftrace)", ["ftrace-function", "ftrace-graph", "ftrace-event", "ftrace-filter",
                          "ftrace-trigger", "trace-cmd", "kernelshark", "trace-event"]),
        ("其他 OS 调度", ["windows-sched", "macos-xnu-sched", "freebsd-sched", "openbsd-sched",
                        "solaris-sched", "rtos-compare", "vxworks-sched", "freertos-sched",
                        "threadx-sched", "zephyr-sched", "rt-thread-sched"]),
        ("调度系统调用", ["sched-syscalls", "sched-params", "sched-affinity-syscall",
                        "sched-prio-syscall", "sched-yield-syscall", "sched-rr-get",
                        "sys-nice", "sys-setpriority", "sys-getpriority"]),
    ],
    "structure": [
        ("体系结构", ["monolith-vs-micro", "multikernel", "layering", "modularity",
                     "extensibility", "kernel-comparison", "hic-arch", "sel4-arch",
                     "qnx-arch", "l4-arch", "static-vs-dynamic", "error-propagation",
                     "fault-isolation", "observability", "logging", "tracing",
                     "crash-dump", "live-patching", "version-migration", "runtime-config"]),
        ("启动与固件", ["boot-process", "secure-boot", "early-output", "kbuild",
                       "kbuild-detail", "system-call", "privilege-ring",
                       "device-tree", "acpi", "devicetree-spec", "dt-bindings", "dt-doc",
                       "device-tree-binding", "fdt-format", "fdt-api", "dt-overlay",
                       "grub", "grub2", "syslinux", "lilo", "coreboot", "coreboot-detail",
                       "edk2", "uefi-boot", "uefi-protocol", "uefi-variable", "uefi-rt",
                       "uefi-memmap", "multiboot-spec", "linuxboot-tiny",
                       "arm-tf", "op-tee", "scmi", "psci", "scpi",
                       "atf-bl31", "atf-bl32", "opensbi-detail", "rustsbi"]),
        ("调试工具", ["kasan", "kmsan", "kcsan", "ubsan", "kfence", "kmemleak", "lkdtm",
                     "gdb-debug", "qemu-debug", "kgdb", "kunit", "syzkaller", "fuzzing",
                     "sparse", "smatch", "coccinelle", "checkpatch", "kernel-doc",
                     "syzbot", "kernelci", "0-day", "kbuild-bot", "bugzilla",
                     "crash", "kdump", "kexec", "kallsyms", "stacktrace",
                     "bug-hunting", "lockdep-report", "sched-debug"]),
        ("工具链与构建", ["toolchain", "linker-script", "elf", "dwarf", "stabs", "coff", "macho",
                         "kconfig", "kconfig-language", "make-targets", "cross-compile",
                         "kbuild-out-of-tree", "kbuild-targets", "kernel-module-api",
                         "module-params", "module-dep", "module-stacking"]),
        ("内核基础设施", ["kmsg", "printk", "dev-printk", "syslog", "netlink", "ioctl",
                          "sysfs", "procfs", "debugfs", "tracefs", "seq-file", "relay",
                          "kernel-panic"]),
        ("数据结构", ["rbtree", "rbtree-api", "radix-tree", "radix-tree-detail", "xarray",
                     "maple-tree", "list-api", "hlist", "kfifo", "ida", "idr", "prio-tree",
                     "interval-tree", "bitmap", "bitops", "asm-locking", "cmp-encoding",
                     "lockless-less", "lifetime", "refcount-kernel", "kref"]),
        ("驱动框架", ["driver-framework", "driver-lifetime", "driver-binding", "driver-override",
                      "async-probe", "deferred-probe", "component-agg", "device-property",
                      "device-links", "firmware-loading", "firmware-api", "kernel-module",
                      "lkmp", "maintainers", "get_maintainer"]),
        ("内核开发流程", ["lwn", "lkml", "kernel-newbies", "subsystem", "net-mail",
                         "stable-api", "ABI-stable", "rust-in-linux", "kspp", "hardening",
                         "security-features",
                         "kernel-2.4", "kernel-2.6", "kernel-3.x", "kernel-4.x",
                         "kernel-5.x", "kernel-6.x", "kernel-next", "stable-kernel",
                         "lts-kernel", "android-common", "rhel-kernel", "debian-kernel",
                         "arch-kernel", "kernel-release", "backport", "regression",
                         "bisect", "lkml-posting", "patch-format", "review-process",
                         "maintainer-entry", "kernel-tree", "coding-style", "doc-guide",
                         "api-doc", "bug-report", "security-bug", "cve-process",
                         "conferences", "mailing-list", "irc", "people"]),
        ("CPU 架构", ["mips-arch", "powerpc-arch", "sparc-arch", "arc-arch", "openrisc",
                      "csky", "loongarch", "hexagon", "um-arch", "parisc-arch",
                      "m68k-arch", "s390-arch", "mcore", "nds32", "sh-arch",
                      "xtensa", "alpha-arch",
                      "armv8-detail", "arm-gic-detail", "arm-power-state",
                      "riscv-hyp", "riscv-smode", "riscv-trap",
                      "x86-paging-detail", "x86-segmentation", "x86-syscall",
                      "x86-smi", "x86-ucode"]),
        ("图形/显示", ["drm-kms-atomic", "drm-fbdev", "drm-gem", "drm-ttm",
                       "i915-drv", "amdgpu-drv", "drm"]),
        ("虚拟化", ["kvm-intel", "kvm-arm", "kvm-riscv", "kvm-mmu", "kvm-iommu",
                    "kvm-api", "xen-hypercall", "xen-grant", "huge-virt", "nest-virt",
                    "virtio-pci", "virtio-mmio", "virtio-ccw", "vhost-user",
                    "pci-pasid", "pci-sriov", "pci-aer", "pci-p2p",
                    "arm-smmu", "intel-iommu", "iommu-map"]),
        ("其他 OS", ["xenomai", "rtai", "rtlinux", "zephyr", "freertos", "contiki",
                     "tinyos", "plan9", "inferno", "helenos", "genode",
                     "fuchsia", "windows-nt", "xnu", "freebsd-kernel", "openbsd-kernel"]),
    ],
    "resource": [
        ("内存分配器", ["buddy-system", "slab-allocator", "slab-ops", "slab-colour",
                       "slab-reclaim", "vmalloc", "vmalloc-detail", "ioremap",
                       "fixmap", "kmap", "highmem", "refcount", "lease",
                       "resource-kernel", "page-flags", "folio", "compound-page",
                       "pfn", "memmap", "section-mem", "memory-model", "devmem"]),
        ("虚拟内存", ["virtual-memory", "page-table", "mmu", "tlb", "tlb-arch", "tlb-management",
                     "page-fault", "demand-paging", "prefetch", "huge-page", "huge-tlb",
                     "thp", "thp-defer", "overcommit", "memory-hotplug", "balloon"]),
        ("页面回收", ["page-reclaim", "page-migration", "swap", "oom", "zram", "zswap",
                     "zsmalloc", "ksm", "cma", "numa", "numa-balance", "mempolicy",
                     "zone-reclaim", "numa-topology", "memory-compaction",
                     "writeback", "writeback-engine", "page-writeback", "dirty-page"]),
        ("内存控制", ["memcg", "memcg-lru", "memcg-oom", "cow", "mmap", "mprotect",
                     "madvise", "dma-iommu", "dma", "iommu", "iommu-api", "smmu",
                     "swiotlb", "dma-buf"]),
        ("IPC", ["ipc", "vdso", "gate-page", "vsyscall", "trampoline"]),
        ("文件系统", ["ext4", "ext4-ondisk", "ext4-journal", "xfs", "xfs-btree", "xfs-journal",
                     "btrfs", "btrfs-cow", "btrfs-subvol", "btrfs-raid", "zfs", "f2fs",
                     "erofs", "nilfs", "fat", "ntfs", "exfat", "tmpfs", "ramfs",
                     "proc", "sysfs-internal", "devfs", "udev", "initramfs", "squashfs",
                     "overlayfs", "unionfs", "fuse", "virtio-fs", "nfs", "cifs",
                     "ocfs2", "gfs2", "ceph", "lustre", "bcachefs"]),
        ("文件操作", ["file-lock", "lease-file", "dnotify", "inotify", "fanotify",
                     "io_uring", "aio", "direct-io", "sync-io", "mmap-io",
                     "splice", "sendfile", "vmsplice", "o_direct", "sync_file_range",
                     "fallocate", "fadvise"]),
        ("I/O 层", ["io-scheduler", "block-layer", "bio", "blk-mq", "blk-cgroup",
                    "blk-throttle", "blk-wbt", "blk-iocost", "blk-stat",
                    "sched-cfq", "sched-deadline-io", "sched-bfq", "sched-mq-deadline",
                    "sched-kyber", "io-priority", "ioprio"]),
        ("设备映射", ["device-mapper", "dm-crypt", "dm-thinp", "dm-cache", "dm-mpath",
                     "dm-verity-target", "dm-writecache", "md-raid", "raid-levels",
                     "lvm", "lvm-thin", "lvm-cache", "lvm-raid", "vdo", "stratis",
                     "bcache"]),
        ("网络栈", ["net-skb", "net-protocol", "net-device", "net-tcp", "net-udp",
                   "net-ip", "net-arp", "net-socket", "net-bridge", "net-vlan",
                   "net-routing", "netfilter", "nftables", "iptables",
                   "net-sched", "tc", "xdp", "af-xdp", "tcp-congestion",
                   "tcp-bbr", "mptcp", "mptcp-path", "wireguard", "tls-kernel",
                   "tcp-offload", "rx-flow", "tx-flow", "net-queuing",
                   "packet-scheduler", "net-stack-tuning", "lwnet",
                   "diag-socket", "sock-diagnose", "net-filter-ebpf",
                   "net-time-stamping", "net-sysfs", "net-procfs",
                   "ethtool", "phy-driver", "mdio", "switchdev", "openvswitch"]),
        ("网络硬件", ["phy-driver", "mdio", "wifi", "bluetooth", "can-bus",
                     "6lowpan", "ieee802154", "nfc"]),
        ("存储硬件", ["nvme", "nvme-queue", "nvme-admin", "scsi", "ata-lib", "ahci",
                     "sdhci", "mmc-core", "mtd", "pcie", "pcie-architecture",
                     "pci-bus", "pci-confspace", "pci-ecam", "pci-msi", "pci-msi-x",
                     "pci-bar", "pci-pcie-cap", "pci-ari", "pci-sriov-cap",
                     "pci-pm", "pci-irq-routing", "pci-aer", "pci-p2p",
                     "cxl", "ccix", "open-capi", "gen-z", "nvlink",
                     "nvdimm", "dax", "fs-dax", "dev-dax", "pmem", "btt"]),
        ("x86 硬件", ["x86-arch", "io-ports", "pic-8259", "pit-8253", "rtc-cmos",
                      "keyboard-8042", "ps2", "serial-uart", "floppy-controller",
                      "vga-text", "vga-graphics", "svga", "edid", "vesa-bios",
                      "framebuffer", "hd44780", "i8042",
                      "cr-registers", "dr-registers", "segment-regs",
                      "gdtr-idtr", "ldtr-tr", "task-state-seg",
                      "call-gate", "interrupt-gate", "trap-gate", "task-gate",
                      "gdt", "idt", "ldt", "protection-ring", "iopl",
                      "smram", "smbase", "a20",
                      "cmos", "memory-map", "bda", "ebda",
                      "bios-ivt", "bios-13h", "bios-10h", "bios-16h",
                      "mmx", "sse", "avx-intel", "amx",
                      "cpuid", "msr", "msr-list", "mtrr", "pat",
                      "sme-amd", "sev", "tdx-intel",
                      "vmx", "svm", "hyperv", "para-virt"]),
        ("x86 中断", ["interrupt-controller", "apic-local", "apic-io", "x2apic",
                      "pic-vs-apic", "ipi", "ipi-arch", "ipi-icr",
                      "sipi", "init-ipc", "tlb-shootdown", "cache-mgnt",
                      "mtrr-msr", "pat-msr", "msi", "interrupt-controller"]),
        ("ACPI", ["acpi-table", "acpi-rsdp", "acpi-rsdt", "acpi-madt", "acpi-fadt",
                  "acpi-dsdt", "acpi-ssdt", "acpi-ns", "acpi-aml",
                  "acpi-pci", "acpi-power", "acpi-dsdt"]),
        ("USB", ["usb-host", "usb-ohci", "usb-uhci", "usb-ehci", "usb-xhci",
                 "usb-gadget", "usb-storage", "usbmouse", "usbhid",
                 "usb-descriptor", "usb-transfer"]),
        ("总线协议", ["i2c-protocol", "i2c-driver", "spi-protocol", "spi-driver",
                     "gpio-driver", "pwm-driver", "serio"]),
        ("驱动子系统", ["drm", "kms", "v4l2", "alsa", "hda", "soundwire",
                        "input-subsystem", "evdev", "watchdog", "led-class",
                        "hwmon", "thermal", "crypto-api", "async-tx",
                        "rng", "pstore", "pstore-ram", "pstore-blk",
                        "mailbox", "rpmsg", "remoteproc",
                        "virtio", "virtio-blk", "virtio-net", "virtio-gpu",
                        "virtio-balloon", "vring", "vhost", "vfio", "uio"]),
        ("加密", ["ocf", "async-crypto", "crypto-sched", "akcipher", "kpp", "aead",
                  "shash", "ahash", "skcipher", "scompress", "crypto-rng",
                  "crypto-test", "crypto-user"]),
        ("存储管理", ["bad-blocks", "ecc", "sector-switch", "btt", "smmu"]),
        ("ARM 架构", ["arm-arch", "armv8-detail", "arm-gic-detail", "arm-power-state"]),
        ("RISC-V 架构", ["riscv-arch", "riscv-hyp", "riscv-smode", "riscv-trap"]),
        ("引导标准", ["bios", "efi", "multiboot", "linuxboot", "coreboot", "uboot", "opensbi"]),
    ],
}

# 生成 SUMMARY
lines = ["# 内核设计 Wiki\n", "[关于此 Wiki](index.md)\n", "---\n"]

for cat, groups in categories.items():
    # 每个大类标题
    cat_labels = {"permission": "权限模型", "scheduling": "调度模型",
                  "structure": "结构模型", "resource": "资源模型"}
    label = cat_labels.get(cat, cat)
    cat_path = f"{cat}/README.md"
    lines.append(f"- [{label}]({cat_path})\n")

    for group_title, prefixes in groups:
        lines.append(f"  - **{group_title}**\n")
        # 收集该分组下的实际文件
        for prefix in prefixes:
            # 查找匹配的 md 文件
            found = False
            for f in os.listdir(os.path.join(wiki, cat)):
                if f.endswith(".md") and (f == f"{prefix}.md" or f.startswith(f"{prefix}-") or f.startswith(f"{prefix}_")):
                    title = f[:-3]
                    lines.append(f"    - [{title}]({cat}/{f})\n")
                    found = True
            # 精确匹配
            if not found and os.path.exists(os.path.join(wiki, cat, f"{prefix}.md")):
                lines.append(f"    - [{prefix}]({cat}/{prefix}.md)\n")

lines.append("\n---\n")
lines.append("## 按系统浏览\n")
for sys in ["seL4", "Linux", "HIC", "QNX", "MINIX", "CHERI", "L4"]:
    lines.append(f"- [{sys}](systems/{sys}.md)\n")
lines.append("\n---\n\n- [贡献指南](CONTRIBUTING.md)\n")

with open(os.path.join(wiki, "SUMMARY.md"), "w") as f:
    f.writelines(lines)

print(f"[OK] 归类 SUMMARY 已生成 ({sum(len(g) for _,g in categories.items())} 个子分组)")
